[package]
name = "qiniu-http"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2018"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu HTTP Interface for Rust"
keywords = ["qiniu", "storage"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_version_runtime = "0.1.5"
lazy_static = "1.4.0"
tempfile = "3.1.0"

qiniu-utils = { version = "0.0.4", path = "../utils" }
