[package]
name = "qiniu-utils"
version = "0.2.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2021"
rust-version = "1.70.0"
license = "MIT"
repository = "https://github.com/qiniu/rust-sdk.git"
homepage = "https://www.qiniu.com"
description = "Qiniu SDK Utilities for Rust"
keywords = ["qiniu", "storage"]

[dependencies]
base64 = "0.13.0"
serde = "1.0.130"
smallstr = "0.3.0"
